version: '3.6'
services:
  webapp:
    build: ./webapp
    ports:
      - 80:80
    volumes:
      - ./webapp/sites-available /etc/apache2/sites-available
      - ./www:/var/www/html
    env_file:
      - .env
  composer:
    image: composer:latest
    command: ["composer", "install"]
    volumes:
      - ./www:/app
  mysql:
    image: mysql:5.7
    container_name: mysql
    restart: unless-stopped
    ports:
      - ${MYSQL_PORT}:3306
    command: |
      --default-authentication-plugin=mysql_native_password
      --character-set-server=utf8
      --collation-server=utf8_general_ci
      --explicit_defaults_for_timestamp=1
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - TZ=${TZ}
    env_file:
      - .env
  pma:
    image: phpmyadmin/phpmyadmin
    restart: always
    links:
      - mysql:mysql
    ports:
      - ${PMA_PORT}:80
    environment:
      PMA_HOST: mysql
      MYSQL_USERNAME: root
      MYSQL_ROOT_PASSWORD: root
